import { useEffect,useId,useMemo,useRef,useState,type PointerEvent as ReactPointerEvent,type ReactNode } from 'react'
import { createPortal } from 'react-dom'
import { AnimatePresence,motion,useReducedMotion } from 'motion/react'
import { haptics } from '../lib/interaction'
import { motionTheme } from '../lib/motionTheme'
import { CloseIcon } from './Icons'
const SNAP_RATIOS=[.2,.55,.9];const VELOCITY_THRESHOLD=.5
const viewportHeight=()=>window.visualViewport?.height||window.innerHeight
function rubberBand(overscroll:number,dimension:number,coefficient=.55){return(1-1/(Math.abs(overscroll)*coefficient/dimension+1))*dimension*Math.sign(overscroll)}
function nearest(value:number,values:number[]){return values.reduce((closest,candidate)=>Math.abs(candidate-value)<Math.abs(closest-value)?candidate:closest)}
export function BottomSheet({open,onClose,title,children}:{open:boolean;onClose:()=>void;title:string;children:ReactNode}){
 const[height,setHeight]=useState(0);const[dragging,setDragging]=useState(false);const startRef=useRef({y:0,height:0,time:0});const samples=useRef<Array<{y:number;time:number}>>([]);const crossedRef=useRef(false);const titleId=useId();const reduced=useReducedMotion();const snaps=useMemo(()=>SNAP_RATIOS.map(r=>Math.round(viewportHeight()*r)),[open])
 useEffect(()=>{if(!open)return;setHeight(snaps[1]||Math.round(viewportHeight()*.55));document.body.classList.add('sg-sheet-open');const key=(e:KeyboardEvent)=>{if(e.key==='Escape')onClose()};window.addEventListener('keydown',key);return()=>{document.body.classList.remove('sg-sheet-open');window.removeEventListener('keydown',key)}},[open,snaps,onClose])
 function down(e:ReactPointerEvent<HTMLDivElement>){e.currentTarget.setPointerCapture(e.pointerId);const now=performance.now();startRef.current={y:e.clientY,height,time:now};samples.current=[{y:e.clientY,time:now}];crossedRef.current=false;setDragging(true)}
 function move(e:ReactPointerEvent<HTMLDivElement>){if(!dragging)return;const now=performance.now();samples.current.push({y:e.clientY,time:now});samples.current=samples.current.filter(s=>now-s.time<=100);const raw=startRef.current.height-(e.clientY-startRef.current.y);const min=snaps[0],max=snaps.at(-1)||viewportHeight();let next=raw;if(raw<min)next=min+rubberBand(raw-min,min);if(raw>max)next=max+rubberBand(raw-max,viewportHeight()-max);setHeight(Math.max(0,next));if(Math.abs(next-startRef.current.height)>=viewportHeight()*.18&&!crossedRef.current){crossedRef.current=true;haptics.light()}}
 function up(){if(!dragging)return;setDragging(false);const list=samples.current,first=list[0],last=list.at(-1);const velocity=first&&last&&last.time>first.time?(last.y-first.y)/(last.time-first.time):0;const min=snaps[0];if(height<min*.85&&velocity>0){onClose();return}let target=nearest(height,snaps);if(Math.abs(-velocity)>VELOCITY_THRESHOLD){const ordered=[...snaps].sort((a,b)=>a-b);const current=ordered.findIndex(v=>v>=height);const index=Math.max(0,current<0?ordered.length-1:current);target=ordered[-velocity>0?Math.min(ordered.length-1,index+1):Math.max(0,index-1)]}setHeight(target);haptics.selection()}
 if(typeof document==='undefined')return null
 return createPortal(<AnimatePresence initial={false}>{open&&<motion.div className="sg-sheet-layer" role="presentation" initial={reduced?false:{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} transition={reduced?{duration:0}:motionTheme.transition.ui}><motion.button className="sg-sheet-scrim" type="button" aria-label="Close" onClick={onClose} initial={reduced?false:{opacity:0}} animate={{opacity:1}} exit={{opacity:0}}/><motion.section className={`sg-bottom-sheet ${dragging?'is-dragging':''}`} role="dialog" aria-modal="true" aria-labelledby={titleId} style={{height}} initial={reduced?false:{y:36,opacity:0,scale:.99}} animate={{y:0,opacity:1,scale:1}} exit={reduced?{opacity:0}:{y:28,opacity:0,scale:.99}} transition={reduced?{duration:0}:motionTheme.transition.ui} layout><div className="sg-sheet-drag" onPointerDown={down} onPointerMove={move} onPointerUp={up} onPointerCancel={up}><span className="sg-sheet-handle" aria-hidden="true"/><strong id={titleId}>{title}</strong><motion.button type="button" className="sg-sheet-close" aria-label={`Close ${title}`} onPointerDown={e=>e.stopPropagation()} onClick={e=>{e.stopPropagation();onClose()}} whileTap={reduced?undefined:{scale:.9}} transition={motionTheme.transition.snap}><CloseIcon/></motion.button></div><div className="sg-sheet-content">{children}</div></motion.section></motion.div>}</AnimatePresence>,document.body)
}