import { useMemo, useState } from 'react'
import { BrandMark } from './BrandMark'
import { Button } from './ui/button'
import { demoChannels, demoFeed } from '../data/demo'
import { BookmarkIcon, HeartIcon, HomeIcon, MessageIcon, SearchIcon, SendIcon } from './Icons'

type LandingPageProps={onConnect:()=>void;onDemo:()=>void;connecting:boolean;backendReady:boolean;booting:boolean;error?:string}

function LandingProductDemo({onConnect}:{onConnect:()=>void}){
 const[saved,setSaved]=useState(()=>new Set<string>())
 const[liked,setLiked]=useState(()=>new Set<string>())
 const posts=useMemo(()=>demoFeed.slice(0,3),[])
 const toggle=(setter:typeof setSaved,current:Set<string>,id:string)=>setter(()=>{const next=new Set(current);next.has(id)?next.delete(id):next.add(id);return next})
 return <div className="sg-marketing-demo sg-marketing-demo-v3" aria-label="Interactive Supergram preview">
  <div className="sg-marketing-demo-sidebar"><div className="sg-marketing-demo-brand"><BrandMark/><strong>Supergram</strong></div><button className="is-active"><HomeIcon/>Home</button><button><SearchIcon/>Explore</button><button><SendIcon/>Create</button><button><span className="sg-marketing-pulse-icon">◌</span>Pulse</button><button><span className="sg-marketing-profile-dot">UD</span>Profile</button></div>
  <div className="sg-marketing-demo-main"><div className="sg-marketing-demo-top"><div><button className="is-active">For You</button><button>Following</button><button>Groups</button></div><Button size="sm" onClick={onConnect}>Use my Telegram</Button></div><div className="sg-marketing-demo-feed"><section className="sg-marketing-catchup"><small>While you were away</small><strong>7 updates worth knowing</strong><p>Two groups accelerated overnight. One conversation may need your input.</p><button>Catch me up</button></section>{posts.map(item=>{const channel=demoChannels.find(source=>source.id===item.channelId)!;const media=item.media&&item.media.kind!=='album'?item.media:null;return <article className="sg-marketing-demo-post" key={item.id}><header><span style={{background:channel.accent}}>{channel.initials}</span><div><strong>{channel.title}</strong><small>{channel.type==='group'?'Group':channel.type==='person'?'Person':'Channel'} · now</small></div></header>{media?<div className="sg-marketing-demo-media" style={{background:media.gradient}}><span>{media.label}</span></div>:null}<p>{item.text}</p><div className="sg-marketing-demo-actions"><span><button className={liked.has(item.id)?'is-active':''} onClick={()=>toggle(setLiked,liked,item.id)} aria-label="React"><HeartIcon/></button><button aria-label="Reply"><MessageIcon/></button><button aria-label="Forward"><SendIcon/></button></span><button className={saved.has(item.id)?'is-active':''} onClick={()=>toggle(setSaved,saved,item.id)} aria-label="Save"><BookmarkIcon/></button></div></article>})}</div></div>
  <aside className="sg-marketing-demo-context"><small>Pulse · now</small><strong>Your network is talking about</strong><div><span>HL</span><p><b>Hyperliquid</b><small>4 sources accelerating</small></p></div><div><span>DC</span><p><b>Devcon</b><small>Media being forwarded</small></p></div><p className="sg-marketing-demo-private">Private context stays private to you.</p></aside>
 </div>
}

const outcomes=[
 ['Understand hundreds of messages faster','Catch-up turns high-volume groups and channels into concise, source-inspectable summaries.'],
 ['See Telegram as media','Photos, video, links, conversations, and topic signals become visual feed objects instead of list rows.'],
 ['Know what your network is moving toward','Pulse and Explore surface real topic velocity, relevant people, media, and communities from permitted context.'],
 ['Move back into conversation instantly','React, reply, and forward through Telegram-compatible actions without rebuilding messaging inside Supergram.'],
 ['Keep AI under your control','Use local summaries or bring your own OpenAI key. Private-chat summarization is separately opt-in.'],
 ['Train relevance over time','More like this, less like this, favorites, hides, saves, and reading behavior tune the experience locally.']
]

export function LandingPage({onConnect,onDemo,connecting,backendReady,booting,error}:LandingPageProps){return <div className="sg-marketing-page">
 <header className="sg-marketing-header"><a href="/" className="sg-marketing-brand"><span><BrandMark/></span><strong>Supergram</strong></a><nav><a href="#product">Product</a><a href="#intelligence">AI</a><a href="#privacy">Privacy</a></nav><div><Button variant="ghost" onClick={onDemo}>Open demo</Button><Button onClick={onConnect} disabled={connecting}>{connecting?'Connecting':backendReady?'Continue with Telegram':'Retry connection'}</Button></div></header>
 <main>
  <section className="sg-marketing-hero" id="product"><div className="sg-marketing-hero-copy"><span className="sg-marketing-kicker">Your world on Telegram, turned into a feed</span><h1>Know what is happening without reading everything.</h1><p>Supergram turns the conversations, communities, channels, and media already in your Telegram account into a personalized living feed with visual discovery, contextual catch-up, and network intelligence.</p><div className="sg-marketing-actions"><Button size="lg" onClick={onConnect} disabled={connecting}>{connecting?'Connecting to Telegram':'Continue with Telegram'}<SendIcon/></Button><Button size="lg" variant="outline" onClick={onDemo}>Open interactive demo</Button></div>{error?<p className="sg-marketing-error" role="alert">{error}</p>:null}<small className="sg-marketing-status">{backendReady?'Telegram connection ready':booting?'Checking connection':'Telegram connection is currently unavailable'}</small></div><div className="sg-marketing-hero-proof"><span>Home · Explore · Create · Pulse · Profile</span><span>BYO OpenAI key optional</span><span>Private context is never public by default</span></div></section>
  <section className="sg-marketing-demo-section"><div className="sg-marketing-section-head"><span>Product preview</span><h2>Telegram is the infrastructure. Supergram is the media layer.</h2><p>The preview uses sample data but mirrors the live information architecture and interaction model.</p></div><LandingProductDemo onConnect={onConnect}/></section>
  <section className="sg-marketing-outcomes"><div className="sg-marketing-section-head"><span>What changes</span><h2>Opening Supergram should answer one question: what is happening in my world?</h2></div><div className="sg-marketing-grid">{outcomes.map(([title,copy],index)=><article key={title}><small>{String(index+1).padStart(2,'0')}</small><h3>{title}</h3><p>{copy}</p></article>)}</div></section>
  <section className="sg-marketing-feature-band" id="intelligence"><div><span>Contextual intelligence</span><h2>Catch-up understands the conversation around a message, not just the last hundred lines.</h2><p>Supergram can extract what changed, decisions, requests, deadlines, and important facts while keeping supporting Telegram messages inspectable. AI content is labeled and uncertainty is preserved.</p></div><div className="sg-marketing-summary-card"><small>AI summary · sources available</small><strong>Venue discussion moved forward and one decision needs input</strong><p>The latest messages point toward BKC, two sponsor conversations progressed, and the consumer-track question remains unresolved.</p><footer><span>Based on 18 messages</span><span>Open sources</span></footer></div></section>
  <section className="sg-marketing-telegram" id="privacy"><div className="sg-marketing-section-head"><span>Privacy boundary</span><h2>Connecting Telegram is not blanket permission.</h2></div><div className="sg-marketing-flow"><article><SearchIcon/><h3>Local by default</h3><p>Basic summaries and ranking signals can stay in the browser.</p></article><article><span className="sg-marketing-flow-symbol">AI</span><h3>Your API key</h3><p>Optional OpenAI summaries use a key you provide, held only in page memory.</p></article><article><MessageIcon/><h3>Private stays private</h3><p>Private-derived intelligence remains visible only to you unless you deliberately publish something.</p></article><article><BookmarkIcon/><h3>Save separately</h3><p>Saving in Supergram does not silently pollute Telegram Saved Messages.</p></article></div></section>
  <section className="sg-marketing-final"><span>Telegram is where conversations happen.</span><h2>Supergram is where conversations become media.</h2><p>Connect the account you already use and turn its activity into a visual, contextual, AI-native view of your world.</p><Button size="lg" onClick={onConnect} disabled={connecting}>{connecting?'Connecting':'Continue with Telegram'}<SendIcon/></Button></section>
 </main>
 <footer className="sg-marketing-footer"><div><BrandMark/><strong>Supergram</strong></div><p>Independent client using the Telegram API. Supergram is not affiliated with Telegram.</p><nav><a href="/privacy.html">Privacy</a><a href="/terms.html">Terms</a></nav></footer>
 </div>}
