import { useState } from 'react'
import type { TelegramAccount,ThemeMode,UserSettings } from '../types'
import { Dialog,DialogContent,DialogDescription,DialogFooter,DialogHeader,DialogTitle } from './ui/dialog'
import { Button } from './ui/button'
import { Switch } from './ui/switch'
import { Avatar,AvatarFallback,AvatarImage } from './ui/avatar'
import { Badge } from './ui/badge'
import { Separator } from './ui/separator'
import { clearOpenAIKey, hasOpenAIKey, saveOpenAIKey } from '../lib/userOpenAI'
import { clearLocalSupergramData } from '../lib/storage'
export function SettingsDialog({open,settings,account,favoriteCount,hiddenSourceCount,onClose,onChange,onResetPersonalization,onLogout}:{open:boolean;settings:UserSettings;account:TelegramAccount|null;favoriteCount:number;hiddenSourceCount:number;onClose:()=>void;onChange:(next:UserSettings)=>void;onResetPersonalization:()=>void;onLogout:()=>void}){
 const update=<K extends keyof UserSettings>(key:K,value:UserSettings[K])=>onChange({...settings,[key]:value})
 const [apiKey,setApiKey]=useState(''); const [keySaved,setKeySaved]=useState(()=>hasOpenAIKey()); const [confirmClear,setConfirmClear]=useState(false)
 const name=[account?.firstName,account?.lastName].filter(Boolean).join(' ')||'Connected account'; const initials=(account?.firstName?.[0]||'T')+(account?.lastName?.[0]||'')
 const storeKey=()=>{const value=apiKey.trim();if(!value)return;saveOpenAIKey(value);setApiKey('');setKeySaved(true);onChange({...settings,summaryProvider:'openai',allowAISummaries:true})}
 const removeKey=()=>{clearOpenAIKey();setKeySaved(false);onChange({...settings,summaryProvider:'local'})}
 const clearLocal=()=>{if(!confirmClear){setConfirmClear(true);return}clearOpenAIKey();clearLocalSupergramData();setKeySaved(false);location.reload()}
 return (
  <Dialog open={open} onOpenChange={v=>!v&&onClose()}><DialogContent className="sg-settings-shadcn"><DialogHeader><DialogTitle>Settings</DialogTitle><DialogDescription>Control AI, recommendations, privacy, appearance, and your Telegram connection.</DialogDescription></DialogHeader><div className="sg-settings-scroll">
       <section className="sg-settings-section"><h3>Profile</h3><div className="sg-profile-settings"><Avatar className="h-12 w-12"><AvatarImage src={account?.avatar}/><AvatarFallback>{initials}</AvatarFallback></Avatar><div className="sg-profile-settings-copy"><strong>{name}</strong>{settings.showTelegramUsername&&account?.username&&<span>@{account.username}</span>}{account?.bio&&<p>{account.bio}</p>}</div></div><div className="sg-settings-row"><span><strong>Show Telegram username</strong><small>Controls whether Supergram surfaces your Telegram username in your local profile UI.</small></span><Switch checked={settings.showTelegramUsername} onCheckedChange={v=>update('showTelegramUsername',v)}/></div></section><Separator/>
       <section className="sg-settings-section"><h3>AI & data</h3><p className="sg-settings-note">Supergram uses OpenAI for summaries and AI transforms only when you add your own API key. There is no local summary fallback. Without a key, discovery becomes media-first.</p><div className="sg-byok-row"><input type="password" autoComplete="off" spellCheck={false} value={apiKey} onChange={e=>setApiKey(e.target.value)} placeholder={keySaved?'OpenAI key connected':'OpenAI API key'} aria-label="OpenAI API key"/><Button size="sm" onClick={storeKey} disabled={!apiKey.trim()}>{keySaved?'Replace':'Use key'}</Button>{keySaved&&<Button variant="ghost" size="sm" onClick={removeKey}>Remove</Button>}</div><div className="sg-settings-row"><span><strong>OpenAI summaries</strong><small>{keySaved?'Your key survives page reloads in this browser tab and clears when the tab or browser session ends.':'Add your own API key to enable summaries and AI transforms.'}</small></span><Switch checked={settings.allowAISummaries&&keySaved} disabled={!keySaved} onCheckedChange={v=>update('allowAISummaries',v)}/></div><div className="sg-settings-row"><span><strong>Model</strong><small>Usage is billed directly to your OpenAI API account.</small></span><input className="sg-settings-input" value={settings.openAIModel} onChange={e=>update('openAIModel',e.target.value.trimStart())} autoComplete="off" spellCheck={false} aria-label="OpenAI model" /></div><div className="sg-settings-row"><span><strong>Summarize private chats</strong><small>Off by default. Private chat text is never sent to OpenAI unless you explicitly enable this.</small></span><Switch checked={settings.summarizePrivateChats} disabled={!keySaved||!settings.allowAISummaries} onCheckedChange={v=>update('summarizePrivateChats',v)}/></div><div className="sg-settings-row"><span><strong>Cross-group topic detection</strong><small>Detect topics across sources for your private Explore and Pulse views. This never exposes group membership to other users.</small></span><Switch checked={settings.allowCrossGroupTopics} onCheckedChange={v=>update('allowCrossGroupTopics',v)}/></div></section><Separator/>
       <section className="sg-settings-section"><h3>Recommendations</h3><div className="sg-settings-row"><span><strong>Use groups</strong><small>Use group activity as a signal for your feed and Pulse.</small></span><Switch checked={settings.useGroupsForRecommendations} onCheckedChange={v=>update('useGroupsForRecommendations',v)}/></div><div className="sg-settings-row"><span><strong>Use channel activity</strong><small>Use followed Telegram channels for discovery and ranking.</small></span><Switch checked={settings.useChannelActivity} onCheckedChange={v=>update('useChannelActivity',v)}/></div><div className="sg-settings-row"><span><strong>Use my message interactions</strong><small>Use local interaction metadata for ranking. Raw message content is not sent as analytics.</small></span><Switch checked={settings.useMessagesForPersonalization} onCheckedChange={v=>update('useMessagesForPersonalization',v)}/></div><div className="sg-settings-row"><span><strong>Private chats in For You</strong><small>Allow relevant incoming private messages in recommendations when AI is available.</small></span><Switch checked={settings.includePrivateChatsInForYou} onCheckedChange={v=>update('includePrivateChatsInForYou',v)}/></div><div className="sg-settings-row"><span><strong>Autoplay video</strong><small>Play visible feed videos automatically.</small></span><Switch checked={settings.autoplay==='on'} onCheckedChange={v=>update('autoplay',v?'on':'off')}/></div><div className="sg-settings-row"><span><strong>Personalization</strong><small>{favoriteCount} favorite sources · {hiddenSourceCount} hidden</small></span><Button variant="outline" size="sm" onClick={onResetPersonalization}>Reset</Button></div></section><Separator/>
       <section className="sg-settings-section"><h3>Social privacy</h3><div className="sg-settings-row"><span><strong>Show mutual groups</strong><small>Off by default. Keep shared-group context private unless you choose otherwise.</small></span><Switch checked={settings.showMutualGroups} onCheckedChange={v=>update('showMutualGroups',v)}/></div><div className="sg-settings-row"><span><strong>Show contacts</strong><small>Off by default. Supergram does not treat Telegram connection as permission to expose your contact graph.</small></span><Switch checked={settings.showContacts} onCheckedChange={v=>update('showContacts',v)}/></div></section><Separator/>
       <section className="sg-settings-section"><h3>Appearance</h3><div className="sg-settings-row"><span><strong>Theme</strong></span><div className="sg-theme-segment">{(['system','light','dark'] as ThemeMode[]).map(mode=><button type="button" key={mode} className={settings.themeMode===mode?'is-active':''} onClick={()=>update('themeMode',mode)}>{mode[0].toUpperCase()+mode.slice(1)}</button>)}</div></div></section><Separator/>
       <section className="sg-settings-section"><h3>Telegram</h3><div className="sg-capability-grid">{Object.entries(account?.capabilities||{}).filter(([,enabled])=>enabled).map(([key])=><Badge key={key}>{key.replace(/([A-Z])/g,' $1').replace(/^./,c=>c.toUpperCase())}</Badge>)}</div></section><Separator/>
       <section className="sg-settings-section"><h3>Privacy & account</h3><p className="sg-settings-note">Local data includes read/saved state, favorites, hidden items, personalization history, and preferences. Clearing it also removes the current browser-session OpenAI key. It does not delete Telegram data.</p><div className="sg-settings-linkrow"><Button variant="outline" asChild><a href="/privacy.html">Privacy</a></Button><Button variant="outline" asChild><a href="/terms.html">Terms</a></Button></div><Button variant={confirmClear?'destructive':'outline'} className="mt-3" onClick={clearLocal}>{confirmClear?'Confirm clear local data':'Clear local data'}</Button>{confirmClear&&<Button variant="ghost" className="mt-3" onClick={()=>setConfirmClear(false)}>Cancel</Button>}<Button variant="ghost" className="sg-settings-danger mt-3 px-0" onClick={onLogout}>Switch Telegram account</Button></section>
       </div><DialogFooter><Button onClick={onClose}>Done</Button></DialogFooter></DialogContent></Dialog>
 );
}