import { useState } from 'react'
import type { TelegramAccount,ThemeMode,UserSettings } from '../types'
import { Dialog,DialogContent,DialogDescription,DialogFooter,DialogHeader,DialogTitle } from './ui/dialog'
import { Button } from './ui/button'
import { Switch } from './ui/switch'
import { Avatar,AvatarFallback,AvatarImage } from './ui/avatar'
import { Badge } from './ui/badge'
import { Separator } from './ui/separator'
import { clearOpenAIKey, hasOpenAIKey, saveOpenAIKey } from '../lib/userOpenAI'
export function SettingsDialog({open,settings,account,favoriteCount,hiddenSourceCount,onClose,onChange,onResetPersonalization,onLogout}:{open:boolean;settings:UserSettings;account:TelegramAccount|null;favoriteCount:number;hiddenSourceCount:number;onClose:()=>void;onChange:(next:UserSettings)=>void;onResetPersonalization:()=>void;onLogout:()=>void}){
 const update=<K extends keyof UserSettings>(key:K,value:UserSettings[K])=>onChange({...settings,[key]:value})
 const [apiKey,setApiKey]=useState(''); const [keySaved,setKeySaved]=useState(()=>hasOpenAIKey())
 const name=[account?.firstName,account?.lastName].filter(Boolean).join(' ')||'Connected account'; const initials=(account?.firstName?.[0]||'T')+(account?.lastName?.[0]||'')
 const storeKey=()=>{if(!apiKey.trim())return;saveOpenAIKey(apiKey.trim());setApiKey('');setKeySaved(true);update('summaryProvider','openai')}
 return <Dialog open={open} onOpenChange={v=>!v&&onClose()}><DialogContent className="sg-settings-shadcn"><DialogHeader><DialogTitle>Settings</DialogTitle><DialogDescription>Control your feed, AI summaries, appearance, and account.</DialogDescription></DialogHeader><div className="sg-settings-scroll">
 <section className="sg-settings-section"><h3>Profile</h3><div className="sg-profile-settings"><Avatar className="h-12 w-12"><AvatarImage src={account?.avatar}/><AvatarFallback>{initials}</AvatarFallback></Avatar><div className="sg-profile-settings-copy"><strong>{name}</strong>{account?.username&&<span>@{account.username}</span>}{account?.bio&&<p>{account.bio}</p>}</div></div></section><Separator/>
 <section className="sg-settings-section"><h3>AI summaries</h3><p className="sg-settings-note">Supergram does not use a shared OpenAI key. Add your own API key to send eligible text directly from this browser to OpenAI. The key stays in this browser session and is never sent to the Supergram backend.</p><div className="sg-byok-row"><input type="password" autoComplete="off" spellCheck={false} value={apiKey} onChange={e=>setApiKey(e.target.value)} placeholder={keySaved?'OpenAI key saved for this session':'sk-…'} aria-label="OpenAI API key"/><Button size="sm" onClick={storeKey} disabled={!apiKey.trim()}>Save key</Button>{keySaved&&<Button variant="ghost" size="sm" onClick={()=>{clearOpenAIKey();setKeySaved(false);update('summaryProvider','local')}}>Remove</Button>}</div><div className="sg-settings-row"><span><strong>Use OpenAI summaries</strong><small>{keySaved?'Uses your API account and selected model.':'Add an API key first.'}</small></span><Switch checked={settings.summaryProvider==='openai'&&keySaved} disabled={!keySaved} onCheckedChange={v=>update('summaryProvider',v?'openai':'local')}/></div><div className="sg-settings-row"><span><strong>Model</strong><small>Model billed to your OpenAI API account.</small></span><input className="sg-settings-input" value={settings.openAIModel} onChange={e=>update('openAIModel',e.target.value)} /></div><div className="sg-settings-row"><span><strong>Summarize private chats</strong><small>Off by default. Private chat text is sent only when you enable this.</small></span><Switch checked={settings.summarizePrivateChats} onCheckedChange={v=>update('summarizePrivateChats',v)}/></div></section><Separator/>
 <section className="sg-settings-section"><h3>Feed</h3><div className="sg-settings-row"><span><strong>Private chats in For You</strong><small>Allow relevant incoming private messages in recommendations.</small></span><Switch checked={settings.includePrivateChatsInForYou} onCheckedChange={v=>update('includePrivateChatsInForYou',v)}/></div><div className="sg-settings-row"><span><strong>Autoplay video</strong><small>Play visible feed videos automatically.</small></span><Switch checked={settings.autoplay==='on'} onCheckedChange={v=>update('autoplay',v?'on':'off')}/></div><div className="sg-settings-row"><span><strong>Personalization</strong><small>{favoriteCount} favorite sources · {hiddenSourceCount} hidden</small></span><Button variant="outline" size="sm" onClick={onResetPersonalization}>Reset</Button></div></section><Separator/>
 <section className="sg-settings-section"><h3>Appearance</h3><div className="sg-settings-row"><span><strong>Theme</strong></span><div className="sg-theme-segment">{(['system','light','dark'] as ThemeMode[]).map(mode=><button key={mode} className={settings.themeMode===mode?'is-active':''} onClick={()=>update('themeMode',mode)}>{mode[0].toUpperCase()+mode.slice(1)}</button>)}</div></div></section><Separator/>
 <section className="sg-settings-section"><h3>Telegram</h3><div className="sg-capability-grid">{Object.entries(account?.capabilities||{}).filter(([,enabled])=>enabled).map(([key])=><Badge key={key}>{key.replace(/([A-Z])/g,' $1').replace(/^./,c=>c.toUpperCase())}</Badge>)}</div></section><Separator/>
 <section className="sg-settings-section"><h3>Account</h3><div className="sg-settings-linkrow"><Button variant="outline" asChild><a href="/privacy.html">Privacy</a></Button><Button variant="outline" asChild><a href="/terms.html">Terms</a></Button></div><Button variant="ghost" className="sg-settings-danger mt-3 px-0" onClick={onLogout}>Switch Telegram account</Button></section>
 </div><DialogFooter><Button onClick={onClose}>Done</Button></DialogFooter></DialogContent></Dialog>
}
