import { useMemo,useState } from 'react'
import type { Channel,SourceType } from '../types'
import { BookmarkIcon, SearchIcon } from './Icons'
import { Dialog,DialogContent,DialogDescription,DialogHeader,DialogTitle } from './ui/dialog'
import { Avatar,AvatarFallback,AvatarImage } from './ui/avatar'
type SourceTab='all'|'favorites'|'channel'|'group'|'person'
function initials(c:Channel){return c.initials||c.title.split(/\s+/).filter(Boolean).slice(0,2).map(p=>p[0]).join('').toUpperCase()||'SG'}
export function SourceBrowser({open,channels,favorites,selectedSource,onClose,onSelect,onFavorite}:{open:boolean;channels:Channel[];favorites:Set<string>;selectedSource:string|null;onClose:()=>void;onSelect:(id:string|null)=>void;onFavorite:(channel:Channel)=>void}){
 const[query,setQuery]=useState('');const[tab,setTab]=useState<SourceTab>('all')
 const visible=useMemo(()=>{const q=query.trim().toLowerCase();return[...channels].filter(c=>{if(tab==='favorites'&&!favorites.has(c.id))return false;if(['channel','group','person'].includes(tab)&&(c.type as SourceType|undefined)!==tab)return false;if(q&&!`${c.title} ${c.username||''}`.toLowerCase().includes(q))return false;return true}).sort((a,b)=>Number(favorites.has(b.id))-Number(favorites.has(a.id))||Number(b.unread||0)-Number(a.unread||0)||a.title.localeCompare(b.title))},[channels,favorites,query,tab])
 return <Dialog open={open} onOpenChange={v=>!v&&onClose()}><DialogContent className="sg2-source-browser max-w-[600px]"><DialogHeader><DialogTitle>Telegram sources</DialogTitle><DialogDescription>Filter the Supergram feed by a person, community, or channel. Messaging itself stays in Telegram.</DialogDescription></DialogHeader><label className="sg2-source-search"><SearchIcon/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search your Telegram graph" autoFocus/></label><div className="sg2-source-tabs">{(['all','favorites','channel','group','person'] as SourceTab[]).map(value=><button key={value} className={tab===value?'is-active':''} onClick={()=>setTab(value)}>{value==='all'?'All':value==='person'?'People':value[0].toUpperCase()+value.slice(1)+(value==='channel'||value==='group'?'s':'')}</button>)}</div><div className="sg2-source-list"><button className={`sg2-source-row ${selectedSource===null?'is-active':''}`} onClick={()=>{onSelect(null);onClose()}}><span className="sg2-source-all">∞</span><span><strong>All permitted sources</strong><small>{channels.length} available in this Telegram account</small></span></button>{visible.map(c=><div className={`sg2-source-row ${selectedSource===c.id?'is-active':''}`} key={c.id}><button className="sg2-source-main" onClick={()=>{onSelect(c.id);onClose()}}><Avatar className="h-11 w-11"><AvatarImage src={c.avatar}/><AvatarFallback style={{background:c.accent||undefined}}>{initials(c)}</AvatarFallback></Avatar><span><strong>{c.title}</strong><small>{c.username?`@${c.username}`:c.type==='person'?'Private source':c.type==='group'?'Community':'Channel'}</small></span>{Number(c.unread||0)>0&&<em>{Number(c.unread||0)>99?'99+':c.unread}</em>}</button><button className={`sg2-source-favorite ${favorites.has(c.id)?'is-active':''}`} onClick={()=>onFavorite(c)} aria-label={favorites.has(c.id)?`Remove ${c.title} from favorites`:`Favorite ${c.title}`}><BookmarkIcon/></button></div>)}</div>{!visible.length&&<div className="sg2-empty-module">No sources match these filters.</div>}</DialogContent></Dialog>
}