import { useMemo,useState } from 'react'
import type { Channel,SourceType } from '../types'
import { BookmarkIcon } from './Icons'
import { Dialog,DialogContent,DialogDescription,DialogHeader,DialogTitle } from './ui/dialog'
import { Input } from './ui/input'
import { Button } from './ui/button'
import { Avatar,AvatarFallback,AvatarImage } from './ui/avatar'
type SourceTab='all'|'favorites'|'channel'|'group'|'person'
function initials(c:Channel){return c.initials||c.title.split(/\s+/).filter(Boolean).slice(0,2).map(p=>p[0]).join('').toUpperCase()||'SG'}
export function SourceBrowser({open,channels,favorites,selectedSource,onClose,onSelect,onFavorite}:{open:boolean;channels:Channel[];favorites:Set<string>;selectedSource:string|null;onClose:()=>void;onSelect:(id:string|null)=>void;onFavorite:(channel:Channel)=>void}){const[query,setQuery]=useState('');const[tab,setTab]=useState<SourceTab>('all');const visible=useMemo(()=>{const q=query.trim().toLowerCase();return[...channels].filter(c=>{if(tab==='favorites'&&!favorites.has(c.id))return false;if(['channel','group','person'].includes(tab)&&(c.type as SourceType|undefined)!==tab)return false;if(q&&!`${c.title} ${c.username||''}`.toLowerCase().includes(q))return false;return true}).sort((a,b)=>Number(favorites.has(b.id))-Number(favorites.has(a.id))||Number(b.unread||0)-Number(a.unread||0)||a.title.localeCompare(b.title))},[channels,favorites,query,tab]);return <Dialog open={open} onOpenChange={v=>!v&&onClose()}><DialogContent className="sg-source-dialog max-w-[520px]"><DialogHeader><DialogTitle>Chats and sources</DialogTitle><DialogDescription>Jump into people, groups, and channels from your Telegram graph.</DialogDescription></DialogHeader><div className="sg-source-controls"><Input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search Telegram" autoFocus/><div className="sg-source-tabs">{(['all','favorites','channel','group','person'] as SourceTab[]).map(value=><button key={value} className={tab===value?'is-active':''} onClick={()=>setTab(value)}>{value==='all'?'All':value==='person'?'People':value[0].toUpperCase()+value.slice(1)+(value==='channel'||value==='group'?'s':'')}</button>)}</div></div><div className="sg-source-list"><button className={`sg-source-list-row ${selectedSource===null?'is-active':''}`} onClick={()=>{onSelect(null);onClose()}}><span className="sg-source-avatar-fallback">∞</span><span><strong>All sources</strong><small>{channels.length} Telegram sources</small></span></button>{visible.map(c=><div className={`sg-source-list-row ${selectedSource===c.id?'is-active':''}`} key={c.id}><button className="sg-source-main" onClick={()=>{onSelect(c.id);onClose()}}><Avatar className="h-11 w-11"><AvatarImage src={c.avatar}/><AvatarFallback style={{background:c.accent||undefined}}>{initials(c)}</AvatarFallback></Avatar><span><strong>{c.title}</strong><small>{c.username?`@${c.username}`:c.type==='person'?'Private chat':c.type==='group'?'Group':'Telegram channel'}</small></span>{Number(c.unread||0)>0&&<em>{Number(c.unread||0)>99?'99+':c.unread}</em>}</button><button className={`sg-source-favorite ${favorites.has(c.id)?'is-active':''}`} onClick={()=>onFavorite(c)} aria-label={favorites.has(c.id)?`Remove ${c.title} from favorites`:`Favorite ${c.title}`}><BookmarkIcon/></button></div>)}</div>{!visible.length&&<div className="sg-source-empty"><strong>No sources found</strong><Button variant="ghost" onClick={()=>{setQuery('');setTab('all')}}>Clear filters</Button></div>}</DialogContent></Dialog>}
