from pathlib import Path

p=Path('src/ProductApp.tsx')
s=p.read_text()
s=s.replace("import { BellIcon, BookmarkIcon, CloseIcon, HomeIcon, ImageIcon, SearchIcon, SettingsIcon } from './components/Icons'", "import { BellIcon, BookmarkIcon, CloseIcon, HomeIcon, ImageIcon, MessageIcon, SearchIcon, SendIcon, SettingsIcon } from './components/Icons'")
s=s.replace("  { id: 'all', label: 'Home', icon: HomeIcon },\n  { id: 'unread', label: 'Unread', icon: BellIcon },\n  { id: 'media', label: 'Media', icon: ImageIcon },\n  { id: 'saved', label: 'Saved', icon: BookmarkIcon }", "  { id: 'all', label: 'Home', icon: HomeIcon },\n  { id: 'media', label: 'Discover', icon: SearchIcon },\n  { id: 'unread', label: 'Activity', icon: BellIcon },\n  { id: 'saved', label: 'Saved', icon: BookmarkIcon }")
s=s.replace("  const [sourceBrowserOpen, setSourceBrowserOpen] = useState(false)", "  const [sourceBrowserOpen, setSourceBrowserOpen] = useState(false)\n  const [discussionItem, setDiscussionItem] = useState<FeedItem | null>(null)")
s=s.replace("<button type=\"button\" className={searchOpen || query ? 'is-active' : ''} onClick={() => setSearchOpen(true)}><span className=\"sg-nav-icon\"><SearchIcon /></span><span>Search</span></button>", "<button type=\"button\" className={searchOpen || query ? 'is-active' : ''} onClick={() => setSearchOpen(true)}><span className=\"sg-nav-icon\"><SearchIcon /></span><span>Search</span></button>\n        <button type=\"button\" onClick={() => setSourceBrowserOpen(true)}><span className=\"sg-nav-icon\"><MessageIcon /></span><span>Chats</span></button>")
s=s.replace("<button type=\"button\" className={settings.feedMode === 'latest' ? 'is-active' : ''} onClick={() => changeFeedMode('latest')}>Latest</button>", "<button type=\"button\" className={settings.feedMode === 'latest' ? 'is-active' : ''} onClick={() => changeFeedMode('latest')}>Following</button>")
s=s.replace("onSourceOpen={source => { setSourceFilter(source.id); setSourceBrowserOpen(true) }}\n                  index={index}", "onSourceOpen={source => { setSourceFilter(source.id); setSourceBrowserOpen(true) }}\n                  onDiscussionOpen={post => setDiscussionItem(post)}\n                  index={index}")
old='''    <aside className="sg-context-rail" aria-label="Telegram context">\n      <section className="sg-context-section">'''
new='''    <aside className={`sg-context-rail ${discussionItem ? 'is-discussion' : ''}`} aria-label="Telegram context">\n      {discussionItem ? <section className="sg-context-section sg-discussion-context">\n        <div className="sg-context-title"><strong>Discussion</strong><button type="button" onClick={() => setDiscussionItem(null)}>Close</button></div>\n        <div className="sg-discussion-origin"><strong>{channelMap.get(discussionItem.channelId)?.title || 'Telegram'}</strong><p>{String(discussionItem.text || '').slice(0,220) || 'Media post'}</p></div>\n        <div className="sg-discussion-prompt"><MessageIcon/><span>Join the Telegram conversation around this post.</span></div>\n        <button type="button" className="sg-discussion-send" onClick={() => setSourceBrowserOpen(true)}><SendIcon/> Open conversation</button>\n      </section> : <>\n      <section className="sg-context-section">'''
s=s.replace(old,new)
s=s.replace('''      <p className="sg-context-note">Public content can move directly into Telegram discussion, forwarding, and Saved Messages.</p>\n    </aside>''','''      <p className="sg-context-note">Public content can move directly into Telegram discussion, forwarding, and Saved Messages.</p>\n      </>}\n    </aside>''')
s=s.replace('''    <nav className="sg-mobile-nav" aria-label="Primary mobile navigation">\n      {nav.map(entry => { const Icon = entry.icon; return <button type="button" key={entry.id} className={filter === entry.id ? 'is-active' : ''} onClick={() => changeFilter(entry.id)} aria-label={entry.label}><Icon />{entry.id === 'unread' && unreadTotal > 0 && <b>{unreadTotal > 99 ? '99+' : unreadTotal}</b>}<span>{filter === entry.id ? entry.label : ''}</span></button> })}\n      <button type="button" onClick={() => setSearchOpen(true)} aria-label="Search"><SearchIcon /><span>{searchOpen ? 'Search' : ''}</span></button>\n    </nav>''','''    <nav className="sg-mobile-nav" aria-label="Primary mobile navigation">\n      <button type="button" className={filter === 'all' ? 'is-active' : ''} onClick={() => changeFilter('all')} aria-label="Home"><HomeIcon/><span>Home</span></button>\n      <button type="button" className={filter === 'media' ? 'is-active' : ''} onClick={() => changeFilter('media')} aria-label="Discover"><SearchIcon/><span>Discover</span></button>\n      <button type="button" onClick={() => setSourceBrowserOpen(true)} aria-label="Chats"><MessageIcon/><span>Chats</span></button>\n      <button type="button" className={filter === 'unread' ? 'is-active' : ''} onClick={() => changeFilter('unread')} aria-label="Activity"><BellIcon/>{unreadTotal > 0 && <b>{unreadTotal > 99 ? '99+' : unreadTotal}</b>}<span>Activity</span></button>\n      <button type="button" onClick={() => setSettingsOpen(true)} aria-label="Profile"><span className="sg-mobile-profile-dot">{me?.avatar ? <img src={me.avatar} alt=""/> : initials(me?.firstName)}</span><span>Profile</span></button>\n    </nav>''')
p.write_text(s)

p=Path('src/components/FeedCard.tsx')
s=p.read_text()
s=s.replace("  onSourceOpen,\n  index = 0", "  onSourceOpen,\n  onDiscussionOpen,\n  index = 0")
s=s.replace("  onSourceOpen?: (channel: Channel) => void\n  index?: number", "  onSourceOpen?: (channel: Channel) => void\n  onDiscussionOpen?: (item: FeedItem) => void\n  index?: number")
# Existing reply button becomes discussion entry point while preserving reply sheet via fallback.
s=s.replace('onClick={() => { haptics.light(); setReplyOpen(true) }} aria-label="Reply"', 'onClick={() => { haptics.light(); onDiscussionOpen ? onDiscussionOpen(item) : setReplyOpen(true) }} aria-label="Discuss"')
p.write_text(s)

p=Path('src/feed.css')
s=p.read_text()
s=s.replace('--sg-bg:#0b1116;','--sg-bg:#0f0f10;').replace('--sg-canvas:#0e141a;','--sg-canvas:#0f0f10;').replace('--sg-surface:#121a22;','--sg-surface:#121214;').replace('--sg-surface-2:#17212b;','--sg-surface-2:#1d1d1f;').replace('--sg-hover:#18242e;','--sg-hover:#1a1a1c;').replace('--sg-border:#222f39;','--sg-border:rgba(255,255,255,.14);').replace('--sg-border-soft:#18232c;','--sg-border-soft:rgba(255,255,255,.08);').replace('--sg-text:#f3f7fa;','--sg-text:#f5f5f7;').replace('--sg-text-2:#9aa9b5;','--sg-text-2:#a1a1a6;').replace('--sg-text-3:#657786;','--sg-text-3:#77777c;')
s=s.replace('--sg-surface:#f7f9fa;','--sg-surface:#f7f7f8;').replace('--sg-surface-2:#eef3f6;','--sg-surface-2:#efeff1;').replace('--sg-hover:#f3f7f9;','--sg-hover:#f7f7f8;').replace('--sg-border:#e2e8ec;','--sg-border:rgba(0,0,0,.13);').replace('--sg-border-soft:#edf1f3;','--sg-border-soft:rgba(0,0,0,.075);').replace('--sg-text:#11181c;','--sg-text:#121214;').replace('--sg-text-2:#687984;','--sg-text-2:#6e6e73;').replace('--sg-text-3:#91a0aa;','--sg-text-3:#98989d;')
s=s.replace('border-radius:5px;overflow:hidden;background:var(--sg-media)', 'border-radius:14px;overflow:hidden;background:var(--sg-media)')
s += '''\n/* 2026 social architecture pass */\n.sg-feed-toolbar{position:sticky;top:0;z-index:35;background:color-mix(in srgb,var(--sg-bg) 92%,transparent);backdrop-filter:blur(18px);border-bottom:1px solid var(--sg-border-soft)}\n.sg-feed-mode button{border-radius:8px}\n.sg-discussion-context{min-height:320px}.sg-discussion-origin{padding:12px 0 16px;border-bottom:1px solid var(--sg-border-soft)}.sg-discussion-origin p{margin:7px 0 0;color:var(--sg-text-2);font-size:13px;line-height:1.45}.sg-discussion-prompt{display:flex;gap:10px;align-items:center;padding:18px 0;color:var(--sg-text-2);font-size:13px}.sg-discussion-prompt svg{width:19px}.sg-discussion-send{height:42px;width:100%;display:flex;align-items:center;justify-content:center;gap:8px;border:0;border-radius:10px;background:var(--sg-blue-strong);color:#fff;font-weight:650}.sg-discussion-send svg{width:18px}.sg-mobile-profile-dot{width:24px;height:24px;border-radius:50%;overflow:hidden;display:grid;place-items:center;background:var(--sg-surface-2);font-size:9px;font-weight:750}.sg-mobile-profile-dot img{width:100%;height:100%;object-fit:cover}\n@media(max-width:760px){.sg-mobile-nav{grid-template-columns:repeat(5,1fr)!important}.sg-mobile-nav button span{display:block!important;font-size:10px}.sg-post{padding:18px 14px 23px}.sg-post-head{margin-bottom:9px}.sg-media{width:calc(100% + 28px);margin-left:-14px;border-radius:0}.sg-feed-toolbar{padding-left:14px;padding-right:14px}}\n'''
p.write_text(s)
